
version: '3'
services:
  raw:
    build: 
      context: .
      dockerfile: ./raw_consumer/Dockerfile.raw
    volumes:
      - ./raw_consumer/input:/app/input
      - ./raw_consumer/output:/app/output
      - ./raw_consumer/log:/app/log
    command: /app/entrypoint.sh
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/log
      - PIPELINE_STAGE=RAW
  preprocessing:
    build: 
      context: .
      dockerfile: ./preprocessing/Dockerfile.preprocessing
    volumes:
      - ./raw_consumer/output:/app/input
      - ./preprocessing/output:/app/output
      - ./preprocessing/log:/app/log
    command: /app/entrypoint.sh
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/log
      - PIPELINE_STAGE=PRE
    depends_on:
      - raw
  infer:
    build: 
      context: .
      dockerfile: ./inference/Dockerfile.infer
    volumes:
      - ./preprocessing/output:/app/input
      - ./inference/output:/app/output
      - ./inference/log:/app/log
    command: /app/entrypoint.sh
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/log
      - PIPELINE_STAGE=INFER
      - ARCH=vit_small
      - PATCH_SZ=8
      - DOWNSAMPLE_SIZE=5000
    depends_on:
      - preprocessing 


