version: '3'
services:
  raw:
    build: 
      context: .
      dockerfile: ./raw_consumer/Dockerfile.raw
    volumes:
      - /data/saas/Nordtind/ES80/ES80-38:/app/input
      - /data/subzerospace/output:/app/output
      - ./raw_consumer/log:/app/log
    command: /app/entrypoint.sh
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/log
      - PIPELINE_STAGE=RAW

  preprocessing:
    build: 
      context: .
      dockerfile: ./preprocessing/Dockerfile.preprocessing
    volumes:
      - /data/subzerospace/output:/app/input
      - /data/subzerospace/pp_output:/app/output
      - ./preprocessing/log:/app/log
    command: /app/entrypoint.sh
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/log
      - PIPELINE_STAGE=PRE
    depends_on:
      - raw

  monitor:
    build: 
      context: ./monitor
      dockerfile: Dockerfile.monitor
    ports:
      - "8050:8050"
    volumes:
      - /data/saas/Nordtind/ES80/ES80-38:/app/input
      - /data/subzerospace/output:/app/output
      - /data/subzerospace/pp_output:/app/pp_output
      - ./raw_consumer/log:/app/logs/raw
      - ./preprocessing/log:/app/logs/preprocessing
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - PP_OUTPUT_DIR=/app/pp_output
      - LOG_DIR=/app/logs
    command: python3 /app/monitor.py
    depends_on:
      - raw
      - preprocessing

  # infer:
  #   build: 
  #     context: .
  #     dockerfile: ./inference/Dockerfile.infer
  #   volumes:
  #     - ./preprocessing/output:/app/input
  #     - ./inference/output:/app/output
  #     - ./inference/log:/app/log
  #   command: /app/entrypoint.sh
  #   environment:
  #     - INPUT_DIR=/app/input
  #     - OUTPUT_DIR=/app/output
  #     - LOG_DIR=/app/log
  #     - PIPELINE_STAGE=INFER
  #     - ARCH=vit_small
  #     - PATCH_SZ=8
  #     - DOWNSAMPLE_SIZE=5000
  #   depends_on:
  #     - preprocessing 


